export const IPC = {
  // Renderer -> Main
  SESSION_CREATE: 'session:create',
  SESSION_STOP: 'session:stop',
  SESSION_KILL: 'session:kill',
  SESSION_INPUT: 'session:input',
  SESSION_RESIZE: 'session:resize',
  SESSION_LIST: 'session:list',
  SESSION_RENAME: 'session:rename',
  SESSION_REMOVE: 'session:remove',
  ENV_LIST: 'environment:list',
  ENV_CREATE: 'environment:create',
  ENV_UPDATE: 'environment:update',
  ENV_DELETE: 'environment:delete',
  PROFILE_LIST: 'profile:list',
  PROFILE_CREATE: 'profile:create',
  PROFILE_UPDATE: 'profile:update',
  PROFILE_DELETE: 'profile:delete',
  WORKSPACE_SAVE: 'workspace:save',
  WORKSPACE_LOAD: 'workspace:load',
  TRANSCRIPTS_LIST: 'transcripts:list',
  DIALOG_OPEN_DIRECTORY: 'dialog:open-directory',
  SCAN_REPOS_DIR: 'scan:repos-dir',
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  CONFIG_GET_DEFAULT_ENV_VARS: 'config:get-default-env-vars',
  CONFIG_SET_DEFAULT_ENV_VARS: 'config:set-default-env-vars',
  CONFIG_GET_DEFAULT_CLI_FLAGS: 'config:get-default-cli-flags',
  CONFIG_SET_DEFAULT_CLI_FLAGS: 'config:set-default-cli-flags',

  TITLEBAR_UPDATE: 'titlebar:update',

  // Git provider & clone
  GIT_PROVIDER_LIST: 'git:provider-list',
  GIT_PROVIDER_CREATE: 'git:provider-create',
  GIT_PROVIDER_UPDATE: 'git:provider-update',
  GIT_PROVIDER_DELETE: 'git:provider-delete',
  GIT_PROVIDER_TEST: 'git:provider-test',
  GIT_PROVIDER_REPOS: 'git:provider-repos',
  GIT_CLONE: 'git:clone',
  GIT_INIT: 'git:init',

  // Vault
  VAULT_GET_CONFIG: 'vault:get-config',
  VAULT_SET_CONFIG: 'vault:set-config',
  VAULT_LOGIN: 'vault:login',
  VAULT_LOGOUT: 'vault:logout',
  VAULT_STATUS: 'vault:status',
  VAULT_TEST_REF: 'vault:test-ref',
  VAULT_LIST_KEYS: 'vault:list-keys',
  VAULT_MIGRATE_SECRET: 'vault:migrate-secret',
  VAULT_LIST_PLAINTEXT: 'vault:list-plaintext',

  // Docs
  DOCS_OPEN: 'docs:open',
  DOCS_THEME_CHANGED: 'docs:theme-changed',

  // Main -> Renderer
  SESSION_DATA: 'session:data',
  SESSION_STATE_CHANGE: 'session:state-change',
  SESSION_EXITED: 'session:exited',
  SESSION_LABEL_CHANGED: 'session:label-changed',
  GIT_CLONE_PROGRESS: 'git:clone-progress',
  VAULT_STATUS_CHANGED: 'vault:status-changed',
} as const;
